### PR TITLE
Add Package todonotes

### PR DESCRIPTION
**Pull request by LlamasAreAwesome**
Package is used to create nice comments at the side of your pdf document.

### CODE REVIEW

**Review by ToHeld — COMMENTED** [review]
Hi, do you acutally use a todolist in the document? Something I use to note something in the document is the newcommand \red. This creates text that is big and red and impossible to miss while looking over the document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% User defined commands

\newcommand{\red}[1]{\textcolor{red}{[\textbf{#1}]}} %% Roter Kommentar
\newcommand{\note}[1]{} %% Mehrzeiliger Kommentar im Text
\newcommand{\STAB}[1]{\begin{tabular}{@{}c@{}}#1\end{tabular}} %% Rotation text in Tabelle

**Comment by LlamasAreAwesome** [comment]
You can easily add a comment by using \todo[options]{your text}. It will place the comment at the side of your PDF without intervene with the formation.

**Comment by LlamasAreAwesome** [comment]
Give it a try ;)

**Review by ToHeld — APPROVED** [review]
I like that

**Pull request merged**
